dist: ubuntu
language: python
python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install python
install:
  - git clone https://github.com/k41zen/SecurityCenter.git
  - pip install -r requirements.txt
before_script:
  - cd scripts
script:
  - python sc-scan-webhook.py
after_success:
